export const en = {
  lang: "en",
  newChat: "New Chat", chat: "Chat", campaigns: "Campaigns", plans: "Plans",
  store: "Store", installedApps: "Apps", profile: "Profile", admin: "Admin",
  today: "Today", yesterday: "Yesterday", last7: "Last 7 days",
  loginTitle: "Welcome to Ninos", loginSub: "AI-powered campaign creation platform",
  withGoogle: "Continue with Google", withGithub: "Continue with GitHub", withApple: "Continue with Apple",
  orEmail: "or continue with email", email: "Email", password: "Password",
  signIn: "Sign In", signUp: "Create Account", noAcc: "Don\'t have an account?", hasAcc: "Already have an account?",
  verifyTitle: "Verify your email", verifyDesc: "6-digit code sent to",
  verify: "Verify", resend: "Resend code",
  termsTitle: "Terms of Use & Privacy", termsAccept: "Accept & Continue",
  termsBody: `This platform complies with LGPD and GDPR.\n\n**1. Responsible use:** Campaigns must comply with platform policies and applicable law.\n\n**2. Real identity:** Creating campaigns with false identity, scams, or fraud is strictly prohibited.\n\n**3. Personal data:** Handled per our Privacy Policy. Deletion available at any time.\n\n**4. Intellectual property:** Generated content belongs to you but must not infringe third-party rights.\n\n**5. Suspension:** Violations result in immediate suspension without refund.\n\nContact: legal@ninos.ai`,
  newsTitle: "What\'s New ✨", newsClose: "Got it", seePlans: "See plans →",
  plansPopTitle: "Choose your plan", startFree: "Start Free", later: "Maybe later",
  sendMsg: "Send", inputPh: "Describe your campaign or ask a question...",
  sugg: ["Create a conversion campaign for Instagram Ads","Analyze Meta Ads algorithm","Optimize Google Ads budget","Persuasive copies for TikTok Ads","E-commerce remarketing strategy","Digital product launch campaign"],
  drafts: "Drafts", inReview: "In Review", accepted: "Accepted", rejected: "Rejected", newCampaign: "New Campaign",
  starter: "Starter", pro: "Pro", business: "Business", mo: "/mo", tokMo: "tokens/mo", popular: "Most Popular", chooseCurr: "Currency:",
  starterF: ["100K tokens/month","Claude Haiku 4.5","5 active campaigns","Basic integrations","Email support"],
  proF: ["350K tokens/month","Claude Sonnet 4.6","Unlimited campaigns","All integrations","Priority support","PDF/CSV/DOCX Export","AI creative generation"],
  bizF: ["500K tokens/month","Claude Opus 4.6","Unlimited campaigns","Dedicated API","Account manager","99.9% SLA","Advanced admin","Unlimited AI creatives"],
  storeTitle: "Integration Store", install: "Install", installed: "Installed", configure: "Configure",
  appsTitle: "Installed Apps", apiKey: "API Key / Token", accountId: "Account ID", limitLabel: "Monthly limit", save: "Save",
  profileTitle: "My Profile", fullName: "Full Name", birthdate: "Date of Birth",
  company: "Company", language: "Language", saveProfile: "Save Profile", changePic: "Change photo",
  adminTitle: "Admin Panel", mrr: "MRR", activeUsers: "Active Users", churn: "Churn", totalCamp: "Campaigns",
  campaignsMod: "Moderation", clearBtn: "Approve", flagBtn: "Flag",
  plansManage: "Plans", tokenUsage: "Token usage today", recentCamp: "Recent Activity",
  darkMode: "Dark mode", lightMode: "Light mode", logout: "Sign out",
  generateCreative: "Generate AI Creative", creativity: "Creativity",
  all: "All",
};
