export const es = {
  lang: "es",
  newChat: "Nuevo Chat", chat: "Chat", campaigns: "Campañas", plans: "Planes",
  store: "Tienda", installedApps: "Apps", profile: "Perfil", admin: "Admin",
  today: "Hoy", yesterday: "Ayer", last7: "Últimos 7 días",
  loginTitle: "Bienvenido a Ninos", loginSub: "Plataforma de campañas con IA",
  withGoogle: "Continuar con Google", withGithub: "Continuar con GitHub", withApple: "Continuar con Apple",
  orEmail: "o continúa con email", email: "Email", password: "Contraseña",
  signIn: "Iniciar sesión", signUp: "Crear cuenta", noAcc: "¿No tienes cuenta?", hasAcc: "¿Ya tienes cuenta?",
  verifyTitle: "Verifica tu email", verifyDesc: "Código de 6 dígitos enviado a",
  verify: "Verificar", resend: "Reenviar código",
  termsTitle: "Términos y Privacidad", termsAccept: "Aceptar y Continuar",
  termsBody: `Esta plataforma cumple con LGPD y GDPR.\n\n**1. Uso responsable:** Las campañas deben cumplir políticas de plataformas y la ley.\n\n**2. Identidad real:** Prohibido crear campañas con identidad falsa o prácticas fraudulentas.\n\n**3. Datos personales:** Tratados según nuestra Política de Privacidad.\n\n**4. Suspensión:** Las violaciones resultan en suspensión inmediata.\n\nContacto: legal@ninos.ai`,
  newsTitle: "Novedades ✨", newsClose: "Entendido", seePlans: "Ver planes →",
  plansPopTitle: "Elige tu plan", startFree: "Comenzar Gratis", later: "Quizás después",
  sendMsg: "Enviar", inputPh: "Describe tu campaña o haz una pregunta...",
  sugg: ["Crear campaña de conversión Instagram Ads","Analizar algoritmo Meta Ads","Optimizar presupuesto Google Ads","Copies persuasivos TikTok Ads","Estrategia remarketing e-commerce","Campaña lanzamiento producto digital"],
  drafts: "Borradores", inReview: "En Revisión", accepted: "Aceptadas", rejected: "Rechazadas", newCampaign: "Nueva Campaña",
  starter: "Starter", pro: "Pro", business: "Business", mo: "/mes", tokMo: "tokens/mes", popular: "Más Popular", chooseCurr: "Moneda:",
  starterF: ["100K tokens/mes","Claude Haiku 4.5","5 campañas activas","Integraciones básicas","Soporte email"],
  proF: ["350K tokens/mes","Claude Sonnet 4.6","Campañas ilimitadas","Todas integraciones","Soporte prioritario","Export PDF/CSV","Creativos IA"],
  bizF: ["500K tokens/mes","Claude Opus 4.6","Campañas ilimitadas","API dedicada","Gestor de cuenta","SLA 99,9%","Admin avanzado","Creativos IA ilimitados"],
  storeTitle: "Tienda de Integraciones", install: "Instalar", installed: "Instalado", configure: "Configurar",
  appsTitle: "Apps Instaladas", apiKey: "API Key / Token", accountId: "Account ID", limitLabel: "Límite mensual", save: "Guardar",
  profileTitle: "Mi Perfil", fullName: "Nombre Completo", birthdate: "Fecha de Nacimiento",
  company: "Empresa", language: "Idioma", saveProfile: "Guardar Perfil", changePic: "Cambiar foto",
  adminTitle: "Panel Admin", mrr: "MRR", activeUsers: "Usuarios Activos", churn: "Churn", totalCamp: "Campañas",
  campaignsMod: "Moderación", clearBtn: "Aprobar", flagBtn: "Señalar",
  plansManage: "Planes", tokenUsage: "Uso tokens hoy", recentCamp: "Actividad Reciente",
  darkMode: "Modo oscuro", lightMode: "Modo claro", logout: "Cerrar sesión",
  generateCreative: "Generar Creativo IA", creativity: "Creatividad",
  all: "Todos",
};
