export const fr = {
  lang: "fr",
  newChat: "Nouveau Chat", chat: "Chat", campaigns: "Campagnes", plans: "Plans",
  store: "Store", installedApps: "Apps", profile: "Profil", admin: "Admin",
  today: "Aujourd\'hui", yesterday: "Hier", last7: "7 derniers jours",
  loginTitle: "Bienvenue sur Ninos", loginSub: "Plateforme de campagnes par IA",
  withGoogle: "Continuer avec Google", withGithub: "Continuer avec GitHub", withApple: "Continuer avec Apple",
  orEmail: "ou continuer avec email", email: "Email", password: "Mot de passe",
  signIn: "Se connecter", signUp: "Créer un compte", noAcc: "Pas de compte?", hasAcc: "Déjà un compte?",
  verifyTitle: "Vérifiez votre email", verifyDesc: "Code à 6 chiffres envoyé à",
  verify: "Vérifier", resend: "Renvoyer le code",
  termsTitle: "Conditions et Confidentialité", termsAccept: "Accepter et Continuer",
  termsBody: `Cette plateforme est conforme au RGPD et à la LGPD.\n\n**1. Utilisation responsable:** Les campagnes doivent respecter les politiques des plateformes.\n\n**2. Identité réelle:** Interdit de créer des campagnes avec fausse identité ou pratiques frauduleuses.\n\n**3. Données personnelles:** Traitées selon notre Politique de Confidentialité.\n\n**4. Suspension:** Les violations entraînent une suspension immédiate.\n\nContact: legal@ninos.ai`,
  newsTitle: "Nouveautés ✨", newsClose: "Compris", seePlans: "Voir les plans →",
  plansPopTitle: "Choisissez votre plan", startFree: "Commencer Gratuitement", later: "Peut-être plus tard",
  sendMsg: "Envoyer", inputPh: "Décrivez votre campagne ou posez une question...",
  sugg: ["Créer campagne conversion Instagram Ads","Analyser algorithme Meta Ads","Optimiser budget Google Ads","Copies persuasifs TikTok Ads","Stratégie remarketing e-commerce","Campagne lancement produit"],
  drafts: "Brouillons", inReview: "En Révision", accepted: "Acceptées", rejected: "Rejetées", newCampaign: "Nouvelle Campagne",
  starter: "Starter", pro: "Pro", business: "Business", mo: "/mois", tokMo: "tokens/mois", popular: "Plus Populaire", chooseCurr: "Devise:",
  starterF: ["100K tokens/mois","Claude Haiku 4.5","5 campagnes actives","Intégrations de base","Support email"],
  proF: ["350K tokens/mois","Claude Sonnet 4.6","Campagnes illimitées","Toutes intégrations","Support prioritaire","Export PDF/CSV","Créatifs IA"],
  bizF: ["500K tokens/mois","Claude Opus 4.6","Campagnes illimitées","API dédiée","Gestionnaire de compte","SLA 99,9%","Admin avancé","Créatifs IA illimités"],
  storeTitle: "Store d\'Intégrations", install: "Installer", installed: "Installé", configure: "Configurer",
  appsTitle: "Apps Installées", apiKey: "Clé API / Token", accountId: "ID de compte", limitLabel: "Limite mensuelle", save: "Sauvegarder",
  profileTitle: "Mon Profil", fullName: "Nom Complet", birthdate: "Date de Naissance",
  company: "Entreprise", language: "Langue", saveProfile: "Sauvegarder", changePic: "Changer photo",
  adminTitle: "Panneau Admin", mrr: "MRR", activeUsers: "Utilisateurs Actifs", churn: "Churn", totalCamp: "Campagnes",
  campaignsMod: "Modération", clearBtn: "Approuver", flagBtn: "Signaler",
  plansManage: "Plans", tokenUsage: "Utilisation tokens", recentCamp: "Activité Récente",
  darkMode: "Mode sombre", lightMode: "Mode clair", logout: "Se déconnecter",
  generateCreative: "Générer Créatif IA", creativity: "Créativité",
  all: "Tous",
};
