export const ja = {
  lang: "ja",
  newChat: "新しいチャット", chat: "チャット", campaigns: "キャンペーン", plans: "プラン",
  store: "ストア", installedApps: "アプリ", profile: "プロフィール", admin: "管理者",
  today: "今日", yesterday: "昨日", last7: "過去7日間",
  loginTitle: "Ninosへようこそ", loginSub: "AIキャンペーン作成プラットフォーム",
  withGoogle: "Googleで続ける", withGithub: "GitHubで続ける", withApple: "Appleで続ける",
  orEmail: "またはメールで続ける", email: "メール", password: "パスワード",
  signIn: "ログイン", signUp: "アカウント作成", noAcc: "アカウントをお持ちでない方？", hasAcc: "すでにアカウントをお持ちの方？",
  verifyTitle: "メールを確認", verifyDesc: "6桁のコードを送信しました",
  verify: "確認", resend: "コードを再送",
  termsTitle: "利用規約とプライバシー", termsAccept: "同意して続ける",
  termsBody: "本プラットフォームはGDPRおよびLGPDに準拠。\n\n**1. 責任ある利用：** キャンペーンはポリシーに従う必要があります。\n\n**2. 実在の身元：** 虚偽の身元や詐欺行為は禁止。\n\n**3. 個人データ：** プライバシーポリシーに従って処理。\n\n**4. 停止：** 違反は即時停止。\n\nお問い合わせ：legal@ninos.ai",
  newsTitle: "新機能 ✨", newsClose: "了解", seePlans: "プランを見る →",
  plansPopTitle: "プランを選択", startFree: "無料で始める", later: "後で",
  sendMsg: "送信", inputPh: "キャンペーンを説明するか、質問を入力...",
  sugg: ["Instagram Ads コンバージョンキャンペーン","Meta Ads アルゴリズム分析","Google Ads 予算最適化","TikTok Ads 説得力あるコピー","ECサイト リマーケティング","デジタル製品ローンチ"],
  drafts: "下書き", inReview: "レビュー中", accepted: "承認済み", rejected: "却下", newCampaign: "新キャンペーン",
  starter: "スターター", pro: "プロ", business: "ビジネス", mo: "/月", tokMo: "トークン/月", popular: "人気", chooseCurr: "通貨：",
  starterF: ["100Kトークン/月","Claude Haiku 4.5","5キャンペーン","基本インテグレーション","メールサポート"],
  proF: ["350Kトークン/月","Claude Sonnet 4.6","無制限キャンペーン","全インテグレーション","優先サポート","PDF/CSV エクスポート","AIクリエイティブ生成"],
  bizF: ["500Kトークン/月","Claude Opus 4.6","無制限キャンペーン","専用API","アカウントマネージャー","SLA 99.9%","高度な管理","AIクリエイティブ無制限"],
  storeTitle: "インテグレーションストア", install: "インストール", installed: "インストール済み", configure: "設定",
  appsTitle: "インストール済みアプリ", apiKey: "APIキー / トークン", accountId: "アカウントID", limitLabel: "月間制限", save: "保存",
  profileTitle: "マイプロフィール", fullName: "フルネーム", birthdate: "生年月日",
  company: "会社名", language: "言語", saveProfile: "プロフィールを保存", changePic: "写真を変更",
  adminTitle: "管理パネル", mrr: "MRR", activeUsers: "アクティブユーザー", churn: "チャーン", totalCamp: "キャンペーン数",
  campaignsMod: "審査", clearBtn: "承認", flagBtn: "フラグ",
  plansManage: "プラン管理", tokenUsage: "本日のトークン", recentCamp: "最近のアクティビティ",
  darkMode: "ダークモード", lightMode: "ライトモード", logout: "サインアウト",
  generateCreative: "AIクリエイティブ生成", creativity: "創造性",
  all: "全て",
};
