export const pt = {
  lang: "pt",
  newChat: "Novo Chat", chat: "Chat", campaigns: "Campanhas", plans: "Planos",
  store: "Store", installedApps: "Apps", profile: "Perfil", admin: "Admin",
  today: "Hoje", yesterday: "Ontem", last7: "Últimos 7 dias",
  loginTitle: "Bem-vindo ao Ninos", loginSub: "Plataforma de campanhas com IA",
  withGoogle: "Continuar com Google", withGithub: "Continuar com GitHub", withApple: "Continuar com Apple",
  orEmail: "ou continue com e-mail", email: "E-mail", password: "Senha",
  signIn: "Entrar", signUp: "Criar conta", noAcc: "Não tem conta?", hasAcc: "Já tem conta?",
  verifyTitle: "Verifique seu e-mail", verifyDesc: "Código de 6 dígitos enviado para",
  verify: "Verificar", resend: "Reenviar código",
  termsTitle: "Termos de Uso e Privacidade", termsAccept: "Aceitar e Continuar",
  termsBody: `Esta plataforma opera em conformidade com a LGPD (Lei nº 13.709/2018) e GDPR.\n\n**1. Uso responsável:** Campanhas devem respeitar as políticas das plataformas e a legislação vigente.\n\n**2. Identidade real:** É proibido criar campanhas com identidade falsa, golpe ou fraude.\n\n**3. Dados pessoais:** Tratados conforme nossa Política de Privacidade. Exclusão disponível a qualquer momento.\n\n**4. Propriedade intelectual:** Conteúdo gerado é seu, mas não pode infringir direitos de terceiros.\n\n**5. Suspensão:** Violações resultam em suspensão imediata sem reembolso.\n\nContato: juridico@ninos.ai`,
  newsTitle: "Novidades ✨", newsClose: "Entendi", seePlans: "Ver planos →",
  plansPopTitle: "Escolha seu plano", startFree: "Começar Grátis", later: "Talvez depois",
  sendMsg: "Enviar", inputPh: "Descreva sua campanha ou faça uma pergunta...",
  sugg: ["Criar campanha de conversão para Instagram Ads","Analisar algoritmo do Meta Ads","Otimizar orçamento no Google Ads","Copies persuasivos para TikTok Ads","Estratégia de remarketing e-commerce","Campanha de lançamento de produto digital"],
  drafts: "Rascunhos", inReview: "Em Análise", accepted: "Aceitas", rejected: "Recusadas", newCampaign: "Nova Campanha",
  starter: "Starter", pro: "Pro", business: "Business", mo: "/mês", tokMo: "tokens/mês", popular: "Mais Popular", chooseCurr: "Moeda:",
  starterF: ["100.000 tokens/mês","Claude Haiku 4.5","5 campanhas ativas","Integrações básicas","Suporte por e-mail"],
  proF: ["350.000 tokens/mês","Claude Sonnet 4.6","Campanhas ilimitadas","Todas as integrações","Suporte prioritário","Export PDF/CSV/DOCX","Geração de criativos IA"],
  bizF: ["500.000 tokens/mês","Claude Opus 4.6","Campanhas ilimitadas","API dedicada","Gerente de conta","SLA 99,9%","Admin avançado","Criativos IA ilimitados"],
  storeTitle: "Store de Integrações", install: "Instalar", installed: "Instalado", configure: "Configurar",
  appsTitle: "Apps Instalados", apiKey: "API Key / Token", accountId: "Account ID", limitLabel: "Limite mensal", save: "Salvar",
  profileTitle: "Meu Perfil", fullName: "Nome Completo", birthdate: "Data de Nascimento",
  company: "Empresa", language: "Idioma", saveProfile: "Salvar Perfil", changePic: "Alterar foto",
  adminTitle: "Painel Admin", mrr: "MRR", activeUsers: "Usuários Ativos", churn: "Churn", totalCamp: "Campanhas",
  campaignsMod: "Moderação", clearBtn: "Aprovar", flagBtn: "Sinalizar",
  plansManage: "Planos", tokenUsage: "Tokens usados hoje", recentCamp: "Atividade Recente",
  darkMode: "Modo escuro", lightMode: "Modo claro", logout: "Sair",
  generateCreative: "Gerar Criativo IA", creativity: "Criatividade",
  all: "Todos",
};
